services:
  db:
    image: postgres:15.9-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=irmin
      - POSTGRES_PASSWORD=irmin
      - POSTGRES_DB=sgptt
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U irmin -d sgptt"] 
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 15s

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elastic-search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    mem_reservation: 2g
    volumes:
      - es_data:/usr/share/elasticsearch/data

  auth-service:
    image: diegoxze35/auth-service:v1.1
    container_name: auth-service
    ports:
      - "8090:8090"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sgptt
      - DATABASE_USER=irmin
      - DATABASE_PASSWORD=irmin
      - JWT_SECRET=mySuperSecureSecretKeyThatContainsAtLeast32Bits
      - PORT=8090
    depends_on:
      - db

  document-builder-service:
    image: irmindev/document-builder-service:1.0
    container_name: document-builder-service
    ports:
      - "8070:8070"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sgptt
      - DATABASE_USER=irmin
      - DATABASE_PASSWORD=irmin
      - PORT=8070
    depends_on:
      - db
      - auth-service

  protocols-service:
    image: diegoxze35/protocols-service:v1
    container_name: protocols-service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sgptt
      - DATABASE_USER=irmin
      - DATABASE_PASSWORD=irmin
      - PORT=8081
      - DATA_AUTH_URL=http://auth-service:8090
      - ELASTIC_SEARCH_URL=http://elastic-search:9200
      - VIEW_PROTOCOL_URL=http://document-builder-service:8070/api/document/protocol/
      - MAX_FILE_SIZE=4MB
      - MAX_MULTIPART_SIZE=5MB
    depends_on:
      - db
      - auth-service
      - elastic-search

  sinodals-service:
    image: irmindev/sinodal-service:1.0
    container_name: sinodals-service
    ports:
      - "8084:8084"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sgptt
      - DATABASE_USER=irmin
      - DATABASE_PASSWORD=irmin
      - PORT=8084
      - DATA_AUTH_URL=http://auth-service:8090
    depends_on:
      - db
      - auth-service
  
  utils-service:
    image: irmindev/utils-service:1.3
    container_name: utils-service
    ports:
      - "8085:8085"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sgptt
      - DATABASE_USER=irmin
      - DATABASE_PASSWORD=irmin
      - PORT=8085
      - DATA_AUTH_URL=http://auth-service:8090
      - ELASTICSEARCH_URL=http://elastic-search:9200
      - DOCUMENT_BUILDER_URL=http://document-builder-service:8070
    depends_on:
      - db
      - auth-service
      - elastic-search
      - document-builder-service
    
volumes:
  pgdata:
    name: pgdata
  es_data:
    name: es_data
    driver: local