apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sgptt-ingress
spec:
  rules:
    - http:
        paths:
        - path: /api/utils
          pathType: Prefix
          backend:
            service:
              name: utils-service
              port:
                number: 8080
        - path: /api/protocols
          pathType: Prefix
          backend:
            service:
              name: protocols-service
              port:
                number: 8087
        - path: /api/auth
          pathType: Prefix
          backend:
            service:
              name: auth-service
              port:
                number: 8090
        - path: /api/assessment
          pathType: Prefix
          backend:
            service:
              name: assessment-service
              port:
                number: 8083
        - path: /api/administration
          pathType: Prefix
          backend:
            service:
              name: administration-service
              port:
                number: 8084
        - path: /api/sinodal
          pathType: Prefix
          backend:
            service:
              name: sinodal-service
              port:
                number: 8085
        - path: /api/document
          pathType: Prefix
          backend:
            service:
              name: document-builder-service
              port:
                number: 8086
