services:
  utils-service:
    build:
        context: .
        dockerfile: Dockerfile2
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sgptt
      - DATABASE_USER=irmin
      - DATABASE_PASSWORD=irmin
      - ELASTICSEARCH_URL=http://elastic-search:9200
      - DATA_AUTH_URL=http://auth-service:8090
    stdin_open: true
    tty: true
    entrypoint: ["./gradlew", "bootRun"]
    volumes:
      - .:/app
      - /app/build
    depends_on:
      - db
      - elastic-search
      - auth-service

  db:
    image: postgres:15.9-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=irmin
      - POSTGRES_PASSWORD=irmin
      - POSTGRES_DB=sgptt
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U irmin -d sgptt"] 
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 15s

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elastic-search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    mem_reservation: 2g
    volumes:
      - es_data:/usr/share/elasticsearch/data

  auth-service:
    image: diegoxze35/auth-service:v1
    ports:
      - "8090:8090"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sgptt
      - DATABASE_USER=irmin
      - DATABASE_PASSWORD=irmin
      - JWT_SECRET=mySuperSecureSecretKeyThatContainsAtLeast32Bits
    depends_on:
      - db

    
volumes:
  pgdata:
  es_data:
    driver: local