apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-deployment
  labels:
    app: sgptt
    service: administration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgptt
      service: administration
  template:
    metadata:
      labels:
        app: sgptt
        service: administration
    spec:
      containers:
        - name: administration-service
          image: ediazh1900/administration-service:v1
          ports:
            - containerPort: 8084
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://db-service:5432/sgptt"
            - name: DATABASE_USER
              value: "irmin"
            - name: DATABASE_PASSWORD
              value: "irmin"
            - name: ELASTICSEARCH_URL
              value: "http://es-service:9200"
            - name: DATA_AUTH_URL
              value: "http://auth-service:8082"
            - name: DOCUMENT_BUILDER_URL
              value: "http://document-builder-service:8086"
            - name: PORT
              value: "8084"