apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-deployment
  labels:
    app: sgptt
    service: assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgptt
      service: assessment
  template:
    metadata:
      labels:
        app: sgptt
        service: assessment
    spec:
      containers:
        - name: assessment-service
          image: ediazh1900/assesment-service:v1
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://db-service:5432/sgptt"
            - name: DATABASE_USER
              value: "irmin"
            - name: DATABASE_PASSWORD
              value: "irmin"
            - name: DATA_AUTH_URL
              value: "http://auth-service:8082"
            - name: PORT
              value: "8083"