apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: sgptt
    service: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgptt
      service: auth
  template:
    metadata:
      labels:
        app: sgptt
        service: auth
    spec:
      containers:
        - name: auth-service
          image: diegoxze35/auth-service:v1.1
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "512Mi"  # Increase the memory request
              cpu: "250m"
            limits:
              memory: "1Gi"    # Increase the memory limit
              cpu: "500m"
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://db-service:5432/sgptt"
            - name: DATABASE_USER
              value: "irmin"
            - name: DATABASE_PASSWORD
              value: "irmin"
            - name: JWT_SECRET
              value: "mySuperSecureSecretKeyThatContainsAtLeast32Bits"
            - name: PORT
              value: "8082"