apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: sgptt
    service: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgptt
      service: db
  template:
    metadata:
      labels:
        app: sgptt
        service: db
    spec:
      containers:
        - name: db
          image: postgres:15.9-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: irmin
            - name: POSTGRES_PASSWORD
              value: irmin
            - name: POSTGRES_DB
              value: sgptt
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - irmin
                - -d
                - sgptt
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - irmin
                - -d
                - sgptt
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
