apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-deployment
  labels:
    app: sgptt
    service: document-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgptt
      service: document-builder
  template:
    metadata:
      labels:
        app: sgptt
        service: document-builder
    spec:
      containers:
        - name: document-builder-service
          image: irmindev/document-builder-service:1.0
          ports:
            - containerPort: 8086
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://db-service:5432/sgptt"
            - name: DATABASE_USER
              value: "irmin"
            - name: DATABASE_PASSWORD
              value: "irmin"
            - name: PORT
              value: "8086"