apiVersion: apps/v1
kind: Deployment
metadata:
  name: protocol-deployment
  labels:
    app: sgptt
    service: protocol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgptt
      service: protocol
  template:
    metadata:
      labels:
        app: sgptt
        service: protocol
    spec:
      containers:
        - name: protocol-service
          image: diegoxze35/protocols-service:v1
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://db-service:5432/sgptt"
            - name: DATABASE_USER
              value: "irmin"
            - name: DATABASE_PASSWORD
              value: "irmin"
            - name: ELASTICSEARCH_URL
              value: "http://es-service:9200"
            - name: DATA_AUTH_URL
              value: "http://auth-service:8082"
            - name: VIEW_PROTOCOL_URL
              value: "http://document-builder-service:8086/api/document/protocol/"
            - name: PORT
              value: "8081"
            - name: MAX_FILE_SIZE
              value: "4MB"
            - name: MAX_MULTIPART_SIZE
              value: "5MB"