apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinodal-deployment
  labels:
    app: sgptt
    service: sinodal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgptt
      service: sinodal
  template:
    metadata:
      labels:
        app: sgptt
        service: sinodal
    spec:
      containers:
        - name: sinodal-service
          image: irmindev/sinodal-service:1.5
          ports:
            - containerPort: 8085
          resources:
            requests:
              memory: "512Mi"  # Increase the memory request
              cpu: "250m"
            limits:
              memory: "1Gi"    # Increase the memory limit
              cpu: "500m"
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://db-service:5432/sgptt"
            - name: DATABASE_USER
              value: "irmin"
            - name: DATABASE_PASSWORD
              value: "irmin"
            - name: PORT
              value: "8085"
            - name: DATA_AUTH_URL
              value: "http://auth-service:8090"