apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils-deployment
  labels:
    app: sgptt
    service: utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgptt
      service: utils
  template:
    metadata:
      labels:
        app: sgptt
        service: utils
    spec:
      containers:
        - name: utils-service
          image: irmindev/utils-service:1.5
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"  # Increase the memory request
              cpu: "250m"
            limits:
              memory: "1Gi"    # Increase the memory limit
              cpu: "500m"
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://db-service:5432/sgptt"
            - name: DATABASE_USER
              value: "irmin"
            - name: DATABASE_PASSWORD
              value: "irmin"
            - name: ELASTICSEARCH_URL
              value: "http://es-service:9200"
            - name: DATA_AUTH_URL
              value: "http://auth-service:8090"
            - name: DOCUMENT_BUILDER_URL
              value: "http://localhost:8081"
            - name: PORT
              value: "8080"