apiVersion: v1
kind: Service
metadata:
  name: administration-service
spec:
  type: ClusterIP
  selector:
    app: sgptt
    service: administration
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084