apiVersion: v1
kind: Service
metadata:
  name: assessment-service
spec:
  type: ClusterIP
  selector:
    app: sgptt
    service: assessment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083