apiVersion: v1
kind: Service
metadata:
  name: es-service
spec:
  type: ClusterIP
  selector:
    app: sgptt
    service: es
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
    - protocol: TCP
      port: 9300
      targetPort: 9300