apiVersion: v1
kind: Service
metadata:
  name: protocols-service
spec:
  type: ClusterIP
  selector:
    app: sgptt
    service: protocol
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081