apiVersion: v1
kind: Service
metadata:
  name: sinodal-service
spec:
  type: ClusterIP
  selector:
    app: sgptt
    service: sinodal
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085