services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - .:/app
      - /app/build
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sgptt
      - DATABASE_USER=irmin
      - DATABASE_PASSWORD=irmin
      - JWT_SECRET=mySuperSecureSecretKeyThatContainsAtLeast32Bits
    container_name: auth-service
    networks:
      - services-net
    stdin_open: true
    entrypoint: ["./gradlew", "bootRun"]
    tty: true
    depends_on:
      - db

  db:
    build:
      context: ./dockerdb
      dockerfile: Dockerfile
    #image: postgres:15.9-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=irmin
      - POSTGRES_PASSWORD=irmin
      - POSTGRES_DB=sgptt
    container_name: db
    networks:
      - services-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U irmin -d sgptt"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 15s

volumes:
  pgdata:
    driver: local

networks:
  services-net:
    name: services