package sgptt.adminsvc.model.domain;

public enum Activity {
    UPLOAD_PROTOCOL_FOR_REGULAR_STUDENTS,
    UPLOAD_PROTOCOL_FOR_FAILED_STUDENTS,
    REGISTER_SINODAL_TO_PROTOCOLS,
    FORCE_PROFESSORS_BECOME_TO_BE_SINODAL,
    PROTOCOL_EVALUATION
}
