services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/build
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/sgptt
      - DATABASE_USER=irmin
      - DATABASE_PASSWORD=irmin
      - DATA_AUTH_URL=http://auth-service:8090
      - PORT=8081
      - MAX_FILE_SIZE=4MB
      - MAX_MULTIPART_SIZE=5MB
    container_name: protocols-service
    networks:
      - services-net
    stdin_open: true
    tty: true
    entrypoint: [ "./gradlew", "bootRun" ]

networks:
  services-net:
    name: services
    external: true